"""
ap-common: Shared functionality for astrophotography tools

Generated By: Cursor (Claude Sonnet 4.5)
"""

from ap_common.fits import get_fits_headers, get_xisf_headers, get_file_headers
from ap_common.normalization import (
    normalize_headers,
    normalize_date,
    normalize_datetime,
    normalize_filterName,
    normalize_target_name,
    normalize_filename,
    denormalize_header,
    FILTER_NORMALIZATION_DATA,
    CONSTANT_NORMALIZATION_DATA,
)
from ap_common.filesystem import move_file, copy_file, delete_empty_directories
from ap_common.metadata import (
    get_metadata,
    enrich_metadata,
    get_filtered_metadata,
    filter_metadata,
)
from ap_common.utils import replace_env_vars, camelCase, get_filenames
from ap_common.progress import progress_iter, ProgressTracker
from ap_common.logging_config import setup_logging, get_logger
from ap_common.constants import (
    # Directory constants
    DIRECTORY_ACCEPT,
    DIRECTORY_STASH,
    # FITS Header constants
    HEADER_DATE_OBS,
    HEADER_IMAGETYP,
    HEADER_TELESCOP,
    HEADER_FOCRATIO,
    HEADER_INSTRUME,
    HEADER_OBJECT,
    HEADER_FILTER,
    HEADER_EXPOSURE,
    HEADER_EXPTIME,
    HEADER_EXP,
    HEADER_CCD_TEMP,
    HEADER_SETTEMP,
    HEADER_SET_TEMP,
    HEADER_SITELAT,
    HEADER_SITELONG,
    HEADER_OBSGEO_B,
    HEADER_OBSGEO_L,
    HEADER_READOUTM,
    # Normalized header names
    NORM_DATE,
    NORM_DATETIME,
    NORM_TYPE,
    NORM_OPTIC,
    NORM_FOCAL_RATIO,
    NORM_CAMERA,
    NORM_TARGETNAME,
    NORM_FILTER,
    NORM_EXPOSURESECONDS,
    NORM_TEMP,
    NORM_SETTEMP,
    NORM_LATITUDE,
    NORM_LONGITUDE,
    NORM_READOUTMODE,
    NORM_PANEL,
    NORM_FILENAME,
    # Image type constants
    TYPE_LIGHT,
    TYPE_DARK,
    TYPE_FLAT,
    TYPE_BIAS,
    CALIBRATION_TYPES,
    # File extension constants
    EXT_FITS,
    EXT_XISF,
    EXT_CR2,
    DEFAULT_FITS_PATTERN,
    DEFAULT_XISF_PATTERN,
    DEFAULT_CR2_PATTERN,
    DEFAULT_IMAGE_PATTERNS,
)

__all__ = [
    # FITS functions
    "get_fits_headers",
    "get_xisf_headers",
    "get_file_headers",
    # Normalization functions
    "normalize_headers",
    "normalize_date",
    "normalize_datetime",
    "normalize_filterName",
    "normalize_target_name",
    "normalize_filename",
    "denormalize_header",
    "FILTER_NORMALIZATION_DATA",
    "CONSTANT_NORMALIZATION_DATA",
    # Filesystem functions
    "move_file",
    "copy_file",
    "delete_empty_directories",
    # Metadata functions
    "get_metadata",
    "enrich_metadata",
    "get_filtered_metadata",
    "filter_metadata",
    # Utility functions
    "replace_env_vars",
    "camelCase",
    "get_filenames",
    # Progress utilities
    "progress_iter",
    "ProgressTracker",
    # Logging functions
    "setup_logging",
    "get_logger",
    # Directory constants
    "DIRECTORY_ACCEPT",
    "DIRECTORY_STASH",
    # FITS Header constants
    "HEADER_DATE_OBS",
    "HEADER_IMAGETYP",
    "HEADER_TELESCOP",
    "HEADER_FOCRATIO",
    "HEADER_INSTRUME",
    "HEADER_OBJECT",
    "HEADER_FILTER",
    "HEADER_EXPOSURE",
    "HEADER_EXPTIME",
    "HEADER_EXP",
    "HEADER_CCD_TEMP",
    "HEADER_SETTEMP",
    "HEADER_SET_TEMP",
    "HEADER_SITELAT",
    "HEADER_SITELONG",
    "HEADER_OBSGEO_B",
    "HEADER_OBSGEO_L",
    "HEADER_READOUTM",
    # Normalized header names
    "NORM_DATE",
    "NORM_DATETIME",
    "NORM_TYPE",
    "NORM_OPTIC",
    "NORM_FOCAL_RATIO",
    "NORM_CAMERA",
    "NORM_TARGETNAME",
    "NORM_FILTER",
    "NORM_EXPOSURESECONDS",
    "NORM_TEMP",
    "NORM_SETTEMP",
    "NORM_LATITUDE",
    "NORM_LONGITUDE",
    "NORM_READOUTMODE",
    "NORM_PANEL",
    "NORM_FILENAME",
    # Image type constants
    "TYPE_LIGHT",
    "TYPE_DARK",
    "TYPE_FLAT",
    "TYPE_BIAS",
    "CALIBRATION_TYPES",
    # File extension constants
    "EXT_FITS",
    "EXT_XISF",
    "EXT_CR2",
    "DEFAULT_FITS_PATTERN",
    "DEFAULT_XISF_PATTERN",
    "DEFAULT_CR2_PATTERN",
    "DEFAULT_IMAGE_PATTERNS",
]
