"""
Calibration frame matching utilities.

Provides simple, flexible utilities for finding matching calibration frames
(darks, flats, bias) based on metadata criteria.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

from typing import Dict, List, Union, Optional
from pathlib import Path
import logging

from ap_common.metadata import get_filtered_metadata, build_normalized_filters
from ap_common.constants import (
    TYPE_MASTER_DARK,
    TYPE_MASTER_FLAT,
    TYPE_MASTER_BIAS,
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    DEFAULT_CALIBRATION_PATTERNS,
)

logger = logging.getLogger(__name__)


def find_matching_darks(
    search_dir: Union[str, Path],
    reference: Dict[str, str],
    match_fields: List[str],
    allow_shorter_exposure: bool = False,
    recursive: bool = True,
    patterns: Optional[List[str]] = None,
    profileFromPath: bool = True,
    printStatus: bool = False,
) -> List[Dict[str, str]]:
    """
    Find dark frames matching reference metadata.

    Args:
        search_dir: Directory to search for dark frames
        reference: Light frame metadata to match against
        match_fields: List of metadata fields that must match exactly
        allow_shorter_exposure: If True, accept darks with exposure < light exposure
                                If False, only accept exact exposure match
        recursive: If True, search subdirectories; if False, search only this directory
        patterns: File patterns to match (defaults to DEFAULT_CALIBRATION_PATTERNS)
        profileFromPath: Extract metadata from path when possible (default True for efficiency)
        printStatus: Show progress output (default False)

    Returns:
        List of metadata dicts for matching darks, sorted by exposure (longest first)
        Each dict includes NORMALIZED_HEADER_FILENAME for the file path

    Example:
        # Search entire blink tree once (efficient!)
        from ap_common.constants import CAMERA, GAIN, OFFSET, SETTEMP, READOUTMODE
        darks = find_matching_darks(
            "/blink",
            light_meta,
            match_fields=[CAMERA, GAIN, OFFSET, SETTEMP, READOUTMODE],
            allow_shorter_exposure=True,
            recursive=True
        )
        # Returns all matching darks from /blink and subdirectories
        # Paths in results show where each dark is located
    """
    # Get light exposure for comparison
    light_exposure = float(reference.get(NORMALIZED_HEADER_EXPOSURESECONDS, -1))

    # Build filter criteria (without exposure initially)
    # Different cameras have different metadata (DSLRs: ISO not gain, no offset/readoutmode)
    filter_criteria = build_normalized_filters(
        reference,
        match_fields,
        overrides={NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK},
    )

    logger.debug(f"Searching for darks with criteria: {filter_criteria}")
    logger.debug(f"Target exposure: {light_exposure}s")

    # Search for all matching darks (any exposure)
    if patterns is None:
        patterns = DEFAULT_CALIBRATION_PATTERNS

    # IMPORTANT: profileFromPath only works with blink/data directory structure
    # For library searches, it should typically be False to read actual file headers
    darks = get_filtered_metadata(
        dirs=[str(search_dir)],
        filters=filter_criteria,
        profileFromPath=profileFromPath,
        patterns=patterns,
        recursive=recursive,
        printStatus=printStatus,
    )

    if not darks:
        logger.debug(
            f"No darks found matching criteria in {search_dir} (recursive={recursive}, patterns={patterns})"
        )
        return []

    logger.debug(f"Found {len(darks)} darks matching criteria")

    # Convert dict to list of metadata dicts
    darks_list = list(darks.values())

    # Filter by exposure logic
    matching = []
    for dark_meta in darks_list:
        dark_exposure = float(dark_meta.get(NORMALIZED_HEADER_EXPOSURESECONDS, -1))

        # Accept if exact match
        if dark_exposure == light_exposure:
            matching.append(dark_meta)
        # Or if shorter exposure allowed
        elif allow_shorter_exposure and dark_exposure < light_exposure:
            matching.append(dark_meta)

    available_exposures = sorted(
        [float(d.get(NORMALIZED_HEADER_EXPOSURESECONDS, -1)) for d in darks_list]
    )
    logger.debug(f"Available dark exposures: {available_exposures}")
    logger.debug(f"After exposure filtering: {len(matching)} matching darks")

    # Sort by exposure (longest first)
    matching.sort(
        key=lambda d: float(d.get(NORMALIZED_HEADER_EXPOSURESECONDS, -1)),
        reverse=True,
    )

    return matching


def find_matching_flats(
    search_dir: Union[str, Path],
    reference: Dict[str, str],
    match_fields: List[str],
    recursive: bool = True,
    patterns: Optional[List[str]] = None,
    profileFromPath: bool = True,
    printStatus: bool = False,
) -> List[Dict[str, str]]:
    """
    Find flat frames matching reference metadata.

    Args:
        search_dir: Directory to search for flat frames
        reference: Light frame metadata to match against
        match_fields: List of metadata fields that must match exactly
        recursive: If True, search subdirectories; if False, search only this directory
        patterns: File patterns to match (defaults to DEFAULT_CALIBRATION_PATTERNS)
        profileFromPath: Extract metadata from path when possible (default True for efficiency)
        printStatus: Show progress output (default False)

    Returns:
        List of metadata dicts for matching flats
        Each dict includes NORMALIZED_HEADER_FILENAME for the file path

    Example:
        # When searching library - include DATE
        from ap_common.constants import CAMERA, FILTER, GAIN, OFFSET, DATE
        flats = find_matching_flats(
            "/library",
            light_meta,
            match_fields=[CAMERA, FILTER, GAIN, OFFSET, DATE],
            recursive=True
        )

        # When checking specific blink dir - DATE doesn't matter, non-recursive
        flats = find_matching_flats(
            "/blink/M31/DATE_2024-01-15",
            light_meta,
            match_fields=[CAMERA, FILTER, GAIN, OFFSET],  # No DATE
            recursive=False  # Just this directory
        )
    """
    # Build filter criteria
    # Different cameras have different metadata (DSLRs: ISO not gain, no offset/readoutmode)
    filter_criteria = build_normalized_filters(
        reference,
        match_fields,
        overrides={NORMALIZED_HEADER_TYPE: TYPE_MASTER_FLAT},
    )

    logger.debug(f"Searching for flats with criteria: {filter_criteria}")

    # Search for matching flats
    if patterns is None:
        patterns = DEFAULT_CALIBRATION_PATTERNS

    flats = get_filtered_metadata(
        dirs=[str(search_dir)],
        filters=filter_criteria,
        profileFromPath=profileFromPath,
        patterns=patterns,
        recursive=recursive,
        printStatus=printStatus,
    )

    logger.debug(f"Found {len(flats)} matching flats")

    # Convert dict to list of metadata dicts
    return list(flats.values())


def find_matching_bias(
    search_dir: Union[str, Path],
    reference: Dict[str, str],
    match_fields: List[str],
    recursive: bool = True,
    patterns: Optional[List[str]] = None,
    profileFromPath: bool = True,
    printStatus: bool = False,
) -> List[Dict[str, str]]:
    """
    Find bias frames matching reference metadata.

    Args:
        search_dir: Directory to search for bias frames
        reference: Light frame metadata to match against
        match_fields: List of metadata fields that must match exactly
        recursive: If True, search subdirectories; if False, search only this directory
        patterns: File patterns to match (defaults to DEFAULT_CALIBRATION_PATTERNS)
        profileFromPath: Extract metadata from path when possible (default True for efficiency)
        printStatus: Show progress output (default False)

    Returns:
        List of metadata dicts for matching bias frames
        Each dict includes NORMALIZED_HEADER_FILENAME for the file path

    Example:
        # Recursive search of library
        from ap_common.constants import CAMERA, GAIN, OFFSET, SETTEMP, READOUTMODE
        bias_frames = find_matching_bias(
            "/library",
            light_meta,
            match_fields=[CAMERA, GAIN, OFFSET, SETTEMP, READOUTMODE],
            recursive=True
        )
    """
    # Build filter criteria
    # Different cameras have different metadata (DSLRs: ISO not gain, no offset/readoutmode)
    filter_criteria = build_normalized_filters(
        reference,
        match_fields,
        overrides={NORMALIZED_HEADER_TYPE: TYPE_MASTER_BIAS},
    )

    logger.debug(f"Searching for bias with criteria: {filter_criteria}")

    # Search for matching bias
    if patterns is None:
        patterns = DEFAULT_CALIBRATION_PATTERNS

    bias = get_filtered_metadata(
        dirs=[str(search_dir)],
        filters=filter_criteria,
        profileFromPath=profileFromPath,
        patterns=patterns,
        recursive=recursive,
        printStatus=printStatus,
    )

    logger.debug(f"Found {len(bias)} matching bias frames")

    # Convert dict to list of metadata dicts
    return list(bias.values())
