"""
FITS and XISF header reading and parsing functions.

Generated By: Cursor (Claude Sonnet 4.5)
"""

import logging
import os
import re
import xisf
from pathlib import Path
from typing import Any, Dict, Optional
from astropy.io import fits
from ap_common.normalization import (
    normalize_headers,
    get_normalized_keys_set,
    get_all_normalized_keys,
    FILTER_NORMALIZATION_DATA,
)
from ap_common.utils import resolve_path

logger = logging.getLogger(__name__)


def apply_file_naming_override(
    file_headers: Dict[str, str],
    filename_headers: Dict[str, str],
) -> Dict[str, str]:
    """
    Apply file naming override logic to file headers.

    Filters out file headers whose normalized form conflicts with filename headers,
    then merges with filename headers taking precedence.

    This implements the core logic for file_naming_override=True behavior:
    - Filename/path values override file header values
    - Handles different raw keys that normalize to same key (DATE vs DATE-OBS)
    - Handles same raw keys (EXPOSURE in both filename and file)

    Args:
        file_headers: Headers read from the file (FITS/XISF keywords)
        filename_headers: Headers parsed from filename/path (via get_file_headers)

    Returns:
        Merged headers dict with filename values taking precedence

    Example:
        # Filename has DATE=2026-02-07, file has DATE-OBS=2026-01-16
        file_headers = {'DATE-OBS': '2026-01-16', 'FILTER': 'H'}
        filename_headers = {'DATE': '2026-02-07'}
        result = apply_file_naming_override(file_headers, filename_headers)
        # Returns: {'FILTER': 'H', 'DATE': '2026-02-07'}
        # DATE-OBS filtered out because it conflicts with filename DATE
    """
    # Build set of normalized keys from filename headers
    normalized_keys_from_filename = get_normalized_keys_set(filename_headers)

    # Filter out file headers whose normalized form conflicts with filename headers
    # (e.g., remove DATE-OBS if filename has DATE, since both → date)
    # Only filter if ALL normalized keys from this header are provided by filename
    if normalized_keys_from_filename:
        filtered_file_headers = {}
        for k, v in file_headers.items():
            # Get all normalized keys this raw header produces
            normalized_keys = get_all_normalized_keys(k)
            # Only filter if ALL normalized keys are already in filename
            if not all(nk in normalized_keys_from_filename for nk in normalized_keys):
                filtered_file_headers[k] = v
        file_headers = filtered_file_headers

    # Merge: filename headers are added last so they take precedence
    output = dict(list(file_headers.items()) + list(filename_headers.items()))
    return output


def get_file_headers(
    filename: str,
    profileFromPath: bool,
    objectFromPath: bool = True,
    normalize: bool = True,
    directory_accept: str = None,
):
    """
    Extracts headers from a filename, optionally normalizing
    and extracting profile/object information from the path.
    Handles special cases for certain header keys and file
    types.

    Args:
        filename: Path to the file
        profileFromPath: Whether to extract profile
            (optic, focal ratio, camera) from path
        objectFromPath: Whether to extract object name from path
        normalize: Whether to normalize the headers
        directory_accept: The "accept" directory name to
            look for (project-specific, defaults to "accept")
    """
    # Normalize path separators to OS-appropriate format
    resolved = resolve_path(filename)
    if resolved is None:
        raise ValueError(f"Could not resolve path: {filename}")
    filename = resolved

    directory_accept = directory_accept or "accept"

    output = {
        "filename": filename,  # before any name manipulations
    }

    # SPECIAL CASES:
    # SET-TEMP: A key with a dash.  Thanks NINA.
    # Handle it before parsing by removing the dash.
    if "SET-TEMP" in filename:
        filename = filename.replace("SET-TEMP", "SETTEMP")

    # Hate special cases so it is optional.
    # Pick OBJECT from the path.  Is the beginning of the
    # dir that is _parent_ of "accept".
    if objectFromPath and directory_accept in filename:
        # inject OBJECT_ at beginning of path before accept.
        # do this by splitting path and finding accept
        filename_split = filename.split(os.sep)
        filename_new = []
        for i in range(0, len(filename_split) - 1):
            icurr = filename_split[i]
            inext = filename_split[i + 1]
            if inext == directory_accept:
                filename_new.append(f"OBJECT_{icurr}")
            else:
                filename_new.append(icurr)
        filename_new.append(filename_split[-1])
        filename = os.sep.join(filename_new)

    # Pick Profile (optic, focal ratio, camera) from path.
    if profileFromPath:
        m = re.match(
            "(.*[\\\\\\/])([^@]*)@f([^+]*)[+]([^\\\\\\/]*)([\\\\\\/].*)", filename
        )
        if m and m.groups() and len(m.groups()) == 5:
            # rebuild path by injecting property prefixes
            p = m.groups()
            filename = f"{p[0]}TELESCOP_{p[1]}_FOCRATIO_{p[2]}_INSTRUME_{p[3]}{p[4]}"

    # just get the headers from the filename itself
    # don't be picky.  get EVERYTHING that could match
    for chunk in os.path.splitext(filename)[0].split(os.sep):
        m1 = re.split("[_]", chunk)
        for i in range(1, len(m1)):
            k = m1[i - 1]
            v = m1[i]
            if not str.isnumeric(k) and k not in output:
                output[k] = v
        for x in m1:
            if "-" in x:
                # Skip hyphen-splitting for known FITS header keywords
                # (e.g., DATE-OBS, SET-TEMP, CCD-TEMP, OBSGEO-B, OBSGEO-L)
                # These use hyphens as part of the key name, not as separators
                if x.upper() in FILTER_NORMALIZATION_DATA:
                    continue
                m2 = re.split("[-]", x)
                k = m2[0]
                v = "-".join(m2[1:])
                if not str.isnumeric(k) and k not in output and v is not None:
                    output[k] = v

    # SPECIAL CASES:
    # .CR2: If extension is .cr2 and TYPE is not already set, default TYPE to LIGHT
    if filename.endswith(".cr2") and "TYPE" not in output:
        output["TYPE"] = "LIGHT"

    # SET-TEMP: The dash was previously removed.  Add it back.
    if "SETTEMP" in output:
        output["SET-TEMP"] = output["SETTEMP"]

    # EXPOSURE: Value may end in "s", starting Dec 2023.  Thanks NINA.
    if "EXPOSURE" in output and "s" in output["EXPOSURE"]:
        output["EXPOSURE"] = output["EXPOSURE"].replace("s", "")

    if normalize:
        output = normalize_headers(output)

    return output


def get_fits_headers(
    filename: str,
    profileFromPath: bool,
    normalize: bool = True,
    file_naming_override: bool = False,
    directory_accept: str = None,
):
    """
    Extracts and normalizes FITS headers from a file,
    optionally overriding with headers from the filename.

    Args:
        filename: Path to the FITS file
        profileFromPath: Whether to extract profile from path
        normalize: Whether to normalize headers
        file_naming_override: Whether to override with headers from filename
        directory_accept: The "accept" directory name (project-specific)
    """
    # Normalize path separators to OS-appropriate format
    resolved = resolve_path(filename)
    if resolved is None:
        raise ValueError(f"Could not resolve path: {filename}")
    filename = resolved

    file_output = {}

    if file_naming_override:
        # Don't normalize yet - use raw keys so filename headers properly
        # override FITS headers with the same raw keys during merge.
        # Normalization happens at the end after all headers are collected.
        file_output = get_file_headers(
            filename,
            normalize=False,
            profileFromPath=profileFromPath,
            directory_accept=directory_accept,
        )

    # Read FITS headers
    with fits.open(filename) as fits_file:
        # get all headers (key/value) as dict from primary image
        output = dict(fits_file[0].header)
    # convert all values to string
    for k in output:
        if output[k] is not None and not isinstance(output[k], str):
            output[k] = str(output[k])

    # Apply file naming override if requested
    if file_naming_override:
        output = apply_file_naming_override(output, file_output)

    # normalize if required
    if normalize:
        output = normalize_headers(output)
    return output


def get_xisf_headers(
    filename: str,
    profileFromPath: bool,
    normalize: bool = True,
    file_naming_override: bool = False,
    directory_accept: str = None,
):
    """
    Extracts and normalizes XISF headers from a file,
    optionally overriding with headers from the filename.

    Args:
        filename: Path to the XISF file
        profileFromPath: Whether to extract profile from path
        normalize: Whether to normalize headers
        file_naming_override: Whether to override with headers from filename
        directory_accept: The "accept" directory name (project-specific)
    """
    # Normalize path separators to OS-appropriate format
    resolved = resolve_path(filename)
    if resolved is None:
        raise ValueError(f"Could not resolve path: {filename}")
    filename = resolved

    file_output = {}
    output = {}

    if file_naming_override:
        # Don't normalize yet - use raw keys so filename headers properly
        # override XISF headers with the same raw keys during merge.
        # Normalization happens at the end after all headers are collected.
        file_output = get_file_headers(
            filename,
            normalize=False,
            profileFromPath=profileFromPath,
            directory_accept=directory_accept,
        )

    # Read XISF headers
    xisf_file = xisf.XISF(filename)
    metadata = xisf_file.get_images_metadata()
    # get all fits headers from metadata, converted to string
    for k in metadata[0]["FITSKeywords"].keys():
        # Skip HISTORY
        if k == "HISTORY":
            continue
        if (
            len(metadata[0]["FITSKeywords"][k]) > 0
            and "value" in metadata[0]["FITSKeywords"][k][0]
        ):
            v = metadata[0]["FITSKeywords"][k][0]["value"]
            if v is not None and str(v) != "":
                output[k] = str(v)

    # Apply file naming override if requested
    if file_naming_override:
        output = apply_file_naming_override(output, file_output)

    # normalize if required
    if normalize:
        output = normalize_headers(output)
    return output


def update_xisf_headers(
    filepath: str,
    updates: Dict[str, str],
    comments: Optional[Dict[str, str]] = None,
    check_existing: bool = True,
) -> bool:
    """
    Update FITS headers in an XISF file.

    Reads the XISF file, updates the specified FITSKeywords, and writes back.
    Preserves image data and all other metadata.

    Args:
        filepath: Path to XISF file
        updates: Dictionary of {header_key: value} to write
        comments: Optional dictionary of {header_key: comment}. If not provided,
                 empty comments are used.
        check_existing: If True, only update if value differs from current value.
                       If False, always write the value. Default: True.

    Returns:
        True if file was modified, False otherwise

    Raises:
        FileNotFoundError: If filepath does not exist
        Exception: If file cannot be read or written
    """
    # Normalize path
    resolved = resolve_path(filepath)
    if resolved is None:
        raise ValueError(f"Could not resolve path: {filepath}")
    filepath = resolved

    file_path = Path(filepath)
    if not file_path.exists():
        raise FileNotFoundError(f"XISF file not found: {filepath}")

    # Read XISF file
    image_metadata: Dict[str, Any] = {}
    xisf_metadata: Dict[str, Any] = {}
    image_data = xisf.XISF.read(
        str(file_path), image_metadata=image_metadata, xisf_metadata=xisf_metadata
    )

    # Ensure FITSKeywords exists
    if "FITSKeywords" not in image_metadata:
        image_metadata["FITSKeywords"] = {}

    # Build dict of current header values if check_existing is True
    current_headers = {}
    if check_existing:
        fits_keywords = image_metadata.get("FITSKeywords", {})
        if isinstance(fits_keywords, dict):
            for key, value_list in fits_keywords.items():
                if isinstance(value_list, list) and len(value_list) > 0:
                    current_val = value_list[0].get("value", "")
                    if isinstance(current_val, (int, float)):
                        current_headers[key.upper()] = str(current_val)
                    else:
                        current_headers[key.upper()] = str(current_val).strip()
                else:
                    current_headers[key.upper()] = str(value_list) if value_list else ""

    # Update headers
    modified = False
    for key, value in updates.items():
        key_upper = key.upper()

        # Check if update is needed
        if check_existing:
            current_value = current_headers.get(key_upper)
            if current_value == value:
                logger.debug(f"Skipping {key}: already set to '{value}'")
                continue

        # Get comment for this key
        comment = ""
        if comments and key in comments:
            comment = comments[key]

        # Update FITSKeywords - values are lists of dicts with 'value' and 'comment'
        image_metadata["FITSKeywords"][key] = [{"value": value, "comment": comment}]
        modified = True
        logger.debug(f"Updated {key} = {value}")

    # Write back if modified
    if modified:
        xisf.XISF.write(
            str(file_path),
            image_data,
            image_metadata=image_metadata,
            xisf_metadata=xisf_metadata,
        )
        logger.debug(f"Wrote updated XISF file: {filepath}")

    return modified
