"""
Unit tests for ap_common.calibration module.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import pytest
from unittest.mock import patch, MagicMock
from ap_common.calibration import (
    find_matching_darks,
    find_matching_flats,
    find_matching_bias,
)
from ap_common.constants import (
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_FILTER,
    NORMALIZED_HEADER_FILENAME,
    TYPE_MASTER_DARK,
    TYPE_MASTER_FLAT,
    TYPE_MASTER_BIAS,
)


class TestFindMatchingDarks:
    """Tests for find_matching_darks function."""

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_exact_exposure_match(self, mock_get_filtered):
        """Test finding darks with exact exposure match."""
        # Setup mock
        mock_get_filtered.return_value = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
            "/path/dark2.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark2.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "120.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            allow_shorter_exposure=False,
            printStatus=False,
        )

        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_EXPOSURESECONDS] == "60.0"
        assert result[0][NORMALIZED_HEADER_FILENAME] == "/path/dark1.fits"

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_shorter_exposure_allowed(self, mock_get_filtered):
        """Test finding darks with shorter exposure when allowed."""
        # Setup mock
        mock_get_filtered.return_value = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "30.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
            "/path/dark2.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark2.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "120.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            allow_shorter_exposure=True,
            printStatus=False,
        )

        # Should get both darks, sorted by exposure (longest first)
        assert len(result) == 2
        assert result[0][NORMALIZED_HEADER_EXPOSURESECONDS] == "60.0"
        assert result[1][NORMALIZED_HEADER_EXPOSURESECONDS] == "30.0"

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_shorter_exposure_not_allowed(self, mock_get_filtered):
        """Test rejecting shorter exposure darks when not allowed."""
        # Setup mock
        mock_get_filtered.return_value = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "30.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "120.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            allow_shorter_exposure=False,
            printStatus=False,
        )

        # Should reject shorter dark when not allowed
        assert len(result) == 0

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_no_matches(self, mock_get_filtered):
        """Test when no darks match."""
        mock_get_filtered.return_value = {}

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            printStatus=False,
        )

        assert len(result) == 0

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_longer_exposure_rejected(self, mock_get_filtered):
        """Test that longer exposure darks are rejected."""
        # Setup mock
        mock_get_filtered.return_value = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "180.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            allow_shorter_exposure=True,  # Even with this, longer should be rejected
            printStatus=False,
        )

        # Longer exposure dark should always be rejected
        assert len(result) == 0

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_recursive_vs_nonrecursive(self, mock_get_filtered):
        """Test that recursive parameter is passed correctly."""
        mock_get_filtered.return_value = {}

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
        }

        # Test recursive=True
        find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
            recursive=True,
            printStatus=False,
        )

        # Check that get_filtered_metadata was called with recursive=True
        call_args = mock_get_filtered.call_args
        assert call_args[1]["recursive"] is True

        # Test recursive=False
        find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
            recursive=False,
            printStatus=False,
        )

        # Check that get_filtered_metadata was called with recursive=False
        call_args = mock_get_filtered.call_args
        assert call_args[1]["recursive"] is False


class TestFindMatchingFlats:
    """Tests for find_matching_flats function."""

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_basic_flat_matching(self, mock_get_filtered):
        """Test basic flat matching."""
        mock_get_filtered.return_value = {
            "/path/flat1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/flat1.fits",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_FILTER: "Ha",
            },
        }

        reference = {
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_FILTER: "Ha",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_flats(
            "/library",
            reference,
            match_fields=[
                NORMALIZED_HEADER_CAMERA,
                NORMALIZED_HEADER_FILTER,
                NORMALIZED_HEADER_GAIN,
            ],
            printStatus=False,
        )

        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_FILTER] == "Ha"

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_multiple_flat_matches(self, mock_get_filtered):
        """Test finding multiple matching flats."""
        mock_get_filtered.return_value = {
            "/path/flat1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/flat1.fits",
                NORMALIZED_HEADER_FILTER: "Ha",
            },
            "/path/flat2.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/flat2.fits",
                NORMALIZED_HEADER_FILTER: "Ha",
            },
        }

        reference = {NORMALIZED_HEADER_FILTER: "Ha"}

        result = find_matching_flats(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_FILTER],
            printStatus=False,
        )

        assert len(result) == 2

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_no_flat_matches(self, mock_get_filtered):
        """Test when no flats match."""
        mock_get_filtered.return_value = {}

        reference = {NORMALIZED_HEADER_FILTER: "Ha"}

        result = find_matching_flats(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_FILTER],
            printStatus=False,
        )

        assert len(result) == 0

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_flat_with_date_matching(self, mock_get_filtered):
        """Test flat matching including date field."""
        from ap_common.constants import NORMALIZED_HEADER_DATE

        mock_get_filtered.return_value = {
            "/path/flat1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/flat1.fits",
                NORMALIZED_HEADER_FILTER: "Ha",
                NORMALIZED_HEADER_DATE: "2024-01-15",
            },
        }

        reference = {
            NORMALIZED_HEADER_FILTER: "Ha",
            NORMALIZED_HEADER_DATE: "2024-01-15",
        }

        result = find_matching_flats(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_FILTER, NORMALIZED_HEADER_DATE],
            printStatus=False,
        )

        assert len(result) == 1


class TestFindMatchingBias:
    """Tests for find_matching_bias function."""

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_basic_bias_matching(self, mock_get_filtered):
        """Test basic bias matching."""
        mock_get_filtered.return_value = {
            "/path/bias1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/bias1.fits",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "100",
            },
        }

        reference = {
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
            NORMALIZED_HEADER_OFFSET: "10",
        }

        result = find_matching_bias(
            "/library",
            reference,
            match_fields=[
                NORMALIZED_HEADER_CAMERA,
                NORMALIZED_HEADER_GAIN,
                NORMALIZED_HEADER_OFFSET,
            ],
            printStatus=False,
        )

        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_GAIN] == "100"

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_multiple_bias_matches(self, mock_get_filtered):
        """Test finding multiple matching bias frames."""
        mock_get_filtered.return_value = {
            "/path/bias1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/bias1.fits",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
            "/path/bias2.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/bias2.fits",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {NORMALIZED_HEADER_CAMERA: "ASI2600MM"}

        result = find_matching_bias(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
            printStatus=False,
        )

        assert len(result) == 2

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_no_bias_matches(self, mock_get_filtered):
        """Test when no bias frames match."""
        mock_get_filtered.return_value = {}

        reference = {NORMALIZED_HEADER_CAMERA: "ASI2600MM"}

        result = find_matching_bias(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
            printStatus=False,
        )

        assert len(result) == 0


class TestIntegration:
    """Integration tests for calibration matching."""

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_type_override_for_darks(self, mock_get_filtered):
        """Test that TYPE is correctly overridden to MASTER_DARK."""
        mock_get_filtered.return_value = {}

        reference = {
            NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,  # This should be overridden
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
        }

        find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
            printStatus=False,
        )

        # Check that build_normalized_filters was called and TYPE was set correctly
        call_args = mock_get_filtered.call_args
        filters = call_args[1]["filters"]
        assert filters[NORMALIZED_HEADER_TYPE] == TYPE_MASTER_DARK

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_type_override_for_flats(self, mock_get_filtered):
        """Test that TYPE is correctly overridden to MASTER_FLAT."""
        mock_get_filtered.return_value = {}

        reference = {
            NORMALIZED_HEADER_TYPE: "LIGHT",  # This should be overridden
            NORMALIZED_HEADER_FILTER: "Ha",
        }

        find_matching_flats(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_FILTER],
            printStatus=False,
        )

        # Check that TYPE was set correctly
        call_args = mock_get_filtered.call_args
        filters = call_args[1]["filters"]
        assert filters[NORMALIZED_HEADER_TYPE] == TYPE_MASTER_FLAT

    @patch("ap_common.calibration.get_filtered_metadata")
    def test_type_override_for_bias(self, mock_get_filtered):
        """Test that TYPE is correctly overridden to MASTER_BIAS."""
        mock_get_filtered.return_value = {}

        reference = {
            NORMALIZED_HEADER_TYPE: "LIGHT",  # This should be overridden
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
        }

        find_matching_bias(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
            printStatus=False,
        )

        # Check that TYPE was set correctly
        call_args = mock_get_filtered.call_args
        filters = call_args[1]["filters"]
        assert filters[NORMALIZED_HEADER_TYPE] == TYPE_MASTER_BIAS
