"""
Unit tests for ap_common.normalization module.

Generated By: Cursor (Claude Sonnet 4.5)
"""

import pytest
from ap_common.normalization import (
    normalize_filterName,
    normalize_date,
    normalize_datetime,
    normalize_target_name,
    normalize_headers,
    denormalize_header,
    normalize_filename,
)


class TestNormalizeFilterName:
    """Tests for normalize_filterName function."""

    def test_baader_uvir_cut(self):
        """Test BaaderUVIRCut normalization."""
        assert normalize_filterName("BaaderUVIRCut") == "UVIR"

    def test_optolong_lextreme(self):
        """Test OptolongLeXtreme normalization."""
        assert normalize_filterName("OptolongLeXtreme") == "LeXtr"

    def test_s2(self):
        """Test S2 normalization."""
        assert normalize_filterName("S2") == "S"

    def test_ha(self):
        """Test Ha normalization."""
        assert normalize_filterName("Ha") == "H"

    def test_o3(self):
        """Test O3 normalization."""
        assert normalize_filterName("O3") == "O"

    def test_empty_string(self):
        """Test empty string normalization."""
        assert normalize_filterName("") == "RGB"

    def test_unknown_filter(self):
        """Test unknown filter returns unchanged."""
        assert normalize_filterName("UnknownFilter") == "UnknownFilter"


class TestNormalizeDate:
    """Tests for normalize_date function."""

    def test_standard_datetime(self):
        """Test standard datetime format."""
        result = normalize_date("2024-01-15T12:30:45")
        # Should subtract 16 hours and format as date
        assert result == "2024-01-14"  # 12:30 - 16 hours = previous day

    def test_with_timezone_z(self):
        """Test datetime with Z timezone."""
        result = normalize_date("2024-01-15T12:30:45Z")
        assert isinstance(result, str)
        assert len(result) == 10  # YYYY-MM-DD format

    def test_with_timezone_offset(self):
        """Test datetime with timezone offset."""
        result = normalize_date("2024-01-15T12:30:45+00:00")
        assert isinstance(result, str)

    def test_with_fractional_seconds(self):
        """Test datetime with fractional seconds."""
        result = normalize_date("2024-01-15T12:30:45.123")
        assert isinstance(result, str)

    def test_date_only_format(self):
        """Test date-only format."""
        result = normalize_date("2024-01-15")
        assert result == "2024-01-15"

    def test_custom_formats(self):
        """Test with custom input and output formats."""
        result = normalize_date(
            "15/01/2024", input_format="%d/%m/%Y", output_format="%Y-%m-%d"
        )
        # normalize_date subtracts 16 hours for timezone adjustment
        # When parsed as datetime (even date-only gets converted), subtracting 16 hours gives previous day
        assert result == "2024-01-14"  # Previous day due to 16-hour timezone offset

    def test_invalid_date(self):
        """Test invalid date returns original string."""
        result = normalize_date("invalid-date")
        assert result == "invalid-date"


class TestNormalizeDatetime:
    """Tests for normalize_datetime function."""

    def test_standard_datetime(self):
        """Test standard datetime format."""
        result = normalize_datetime("2024-01-15T12:30:45")
        assert isinstance(result, str)
        assert "_" in result  # Should be YYYY-MM-DD_HH-MM-SS format

    def test_date_only_to_datetime(self):
        """Test date-only input converted to datetime."""
        result = normalize_datetime("2024-01-15")
        assert isinstance(result, str)
        assert "_" in result

    def test_with_timezone(self):
        """Test datetime with timezone."""
        result = normalize_datetime("2024-01-15T12:30:45Z")
        assert isinstance(result, str)

    def test_custom_formats(self):
        """Test with custom formats."""
        result = normalize_datetime(
            "15/01/2024 12:30:45",
            input_format="%d/%m/%Y %H:%M:%S",
            output_format="%Y-%m-%d_%H-%M-%S",
        )
        assert isinstance(result, str)


class TestNormalizeTargetName:
    """Tests for normalize_target_name function."""

    def test_simple_target(self):
        """Test simple target name."""
        result = normalize_target_name("M42")
        assert result == ["M42", ""]

    def test_target_with_panel(self):
        """Test target name with panel."""
        result = normalize_target_name("M42 Panel 1")
        assert result == ["M42", "1"]

    def test_target_with_quotes(self):
        """Test target name with single quotes."""
        result = normalize_target_name("M'42")
        assert result == ["M42", ""]

    def test_target_with_panel_and_quotes(self):
        """Test target with panel and quotes."""
        result = normalize_target_name("M'42 Panel 2")
        assert result == ["M42", "2"]

    def test_no_panel_match(self):
        """Test target without panel pattern."""
        result = normalize_target_name("Some Target")
        assert result == ["Some Target", ""]


class TestNormalizeHeaders:
    """Tests for normalize_headers function."""

    def test_basic_normalization(self):
        """Test basic header normalization."""
        headers = {"FILTER": "Ha", "EXPOSURE": "60.0", "IMAGETYP": "light"}
        result = normalize_headers(headers)
        assert "filter" in result
        assert result["filter"] == "H"  # Ha -> H
        assert "exposureseconds" in result
        assert result["exposureseconds"] == "60.00"

    def test_date_obs_normalization(self):
        """Test DATE-OBS normalization."""
        headers = {"DATE-OBS": "2024-01-15T12:30:45"}
        result = normalize_headers(headers)
        assert "date" in result
        assert "datetime" in result

    def test_target_name_extraction(self):
        """Test target name panel extraction."""
        headers = {"OBJECT": "M42 Panel 1"}
        result = normalize_headers(headers)
        assert result["targetname"] == "M42"
        assert result["panel"] == "1"

    def test_constant_normalization(self):
        """Test constant normalization."""
        headers = {"camera": "DWARFIII"}
        result = normalize_headers(headers)
        assert result["focal_ratio"] == "4.3"
        assert result["type"] == "LIGHT"

    def test_lowercase_conversion(self):
        """Test that unknown headers are lowercased."""
        headers = {"UNKNOWN_HEADER": "value"}
        result = normalize_headers(headers)
        assert "unknown_header" in result
        assert result["unknown_header"] == "value"

    def test_multiple_normalizations(self):
        """Test multiple header normalizations."""
        headers = {
            "FILTER": "Ha",
            "EXPOSURE": "120.5",
            "CCD-TEMP": "25.0",
            "TELESCOP": "Refractor",
            "INSTRUME": "Camera1",
        }
        result = normalize_headers(headers)
        assert result["filter"] == "H"
        assert result["exposureseconds"] == "120.50"
        assert result["temp"] == "25.00"
        assert result["optic"] == "Refractor"
        assert result["camera"] == "Camera1"


class TestDenormalizeHeader:
    """Tests for denormalize_header function."""

    def test_denormalize_exposure(self):
        """Test denormalizing exposureseconds."""
        result = denormalize_header("exposureseconds")
        assert result in ["EXPOSURE", "EXPTIME", "EXP"]

    def test_denormalize_filter(self):
        """Test denormalizing filter."""
        result = denormalize_header("filter")
        assert result == "FILTER"

    def test_denormalize_unknown(self):
        """Test denormalizing unknown header."""
        result = denormalize_header("unknown_header")
        assert result is None


class TestNormalizeFilename:
    """Tests for normalize_filename function."""

    def test_bias_filename(self):
        """Test BIAS filename normalization."""
        headers = {
            "type": "BIAS",
            "optic": "Refractor",
            "camera": "Camera1",
            "date": "2024-01-15",
            "exposureseconds": "0.00",
            "datetime": "2024-01-15_12-30-45",
            "filter": "None",
        }
        result = normalize_filename("/output", "test.fits", headers)
        assert "BIAS" not in result  # Type not in path for bias
        assert "Refractor+Camera1" in result
        assert "2024-01-15" in result

    def test_dark_filename(self):
        """Test DARK filename normalization."""
        headers = {
            "type": "DARK",
            "optic": "Refractor",
            "camera": "Camera1",
            "date": "2024-01-15",
            "exposureseconds": "300.00",
            "datetime": "2024-01-15_12-30-45",
            "filter": "None",
        }
        result = normalize_filename("/output", "test.fits", headers)
        assert "Refractor+Camera1" in result
        assert "300.00" in result

    def test_light_filename(self):
        """Test LIGHT filename normalization."""
        headers = {
            "type": "LIGHT",
            "optic": "Refractor",
            "camera": "Camera1",
            "focal_ratio": "5.6",
            "date": "2024-01-15",
            "exposureseconds": "120.00",
            "datetime": "2024-01-15_12-30-45",
            "filter": "Ha",
            "targetname": "M42",
        }
        result = normalize_filename(
            "/output", "test.fits", headers, statedir="10_Blink"
        )
        assert "Refractor@f5.6+Camera1" in result
        assert "10_Blink" in result
        assert "M42" in result
        assert "2024-01-15" in result

    def test_missing_required_header(self):
        """Test that missing required header raises exception."""
        headers = {
            "type": "LIGHT",
            "optic": "Refractor",
            # Missing other required headers
        }
        with pytest.raises(Exception, match="missing required header"):
            normalize_filename("/output", "test.fits", headers)

    def test_with_settemp(self):
        """Test filename with set temperature."""
        headers = {
            "type": "LIGHT",
            "optic": "Refractor",
            "camera": "Camera1",
            "focal_ratio": "5.6",
            "date": "2024-01-15",
            "exposureseconds": "120.00",
            "datetime": "2024-01-15_12-30-45",
            "filter": "Ha",
            "targetname": "M42",
            "settemp": "-10.00",
        }
        result = normalize_filename("/output", "test.fits", headers)
        assert "SETTEMP_-10.00" in result

    def test_with_optional_headers(self):
        """Test filename with optional headers like hfr, stars."""
        headers = {
            "type": "LIGHT",
            "optic": "Refractor",
            "camera": "Camera1",
            "focal_ratio": "5.6",
            "date": "2024-01-15",
            "exposureseconds": "120.00",
            "datetime": "2024-01-15_12-30-45",
            "filter": "Ha",
            "targetname": "M42",
            "hfr": "2.5",
            "stars": "150",
        }
        result = normalize_filename("/output", "test.fits", headers)
        assert "HFR_2.5" in result
        assert "STARS_150" in result
