"""
Unit tests for ap_common.calibration module.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import pytest
from unittest.mock import patch, MagicMock
from ap_common.calibration import (
    find_matching_darks,
    find_matching_flats,
    find_matching_bias,
    find_matching_darks_from_cache,
    find_matching_flats_from_cache,
    find_matching_bias_from_cache,
)
from ap_common.constants import (
    NORMALIZED_HEADER_TYPE,
    NORMALIZED_HEADER_CAMERA,
    NORMALIZED_HEADER_GAIN,
    NORMALIZED_HEADER_OFFSET,
    NORMALIZED_HEADER_SETTEMP,
    NORMALIZED_HEADER_READOUTMODE,
    NORMALIZED_HEADER_EXPOSURESECONDS,
    NORMALIZED_HEADER_FILTER,
    NORMALIZED_HEADER_FILENAME,
    TYPE_MASTER_DARK,
    TYPE_MASTER_FLAT,
    TYPE_MASTER_BIAS,
)


class TestFindMatchingDarks:
    """Tests for find_matching_darks function."""

    @patch("ap_common.calibration.get_metadata")
    def test_exact_exposure_match(self, mock_get_metadata):
        """Test finding darks with exact exposure match."""
        # Setup mock
        mock_get_metadata.return_value = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
                NORMALIZED_HEADER_GAIN: "100",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
            "/path/dark2.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark2.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_EXPOSURESECONDS: "120.0",
                NORMALIZED_HEADER_GAIN: "100",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            allow_shorter_exposure=False,
            printStatus=False,
        )

        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_EXPOSURESECONDS] == "60.0"
        assert result[0][NORMALIZED_HEADER_FILENAME] == "/path/dark1.fits"

    @patch("ap_common.calibration.get_metadata")
    def test_shorter_exposure_allowed(self, mock_get_metadata):
        """Test finding darks with shorter exposure when allowed."""
        # Setup mock
        mock_get_metadata.return_value = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_EXPOSURESECONDS: "30.0",
                NORMALIZED_HEADER_GAIN: "100",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
            "/path/dark2.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark2.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
                NORMALIZED_HEADER_GAIN: "100",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "120.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            allow_shorter_exposure=True,
            printStatus=False,
        )

        # Should get both darks, sorted by exposure (longest first)
        assert len(result) == 2
        assert result[0][NORMALIZED_HEADER_EXPOSURESECONDS] == "60.0"
        assert result[1][NORMALIZED_HEADER_EXPOSURESECONDS] == "30.0"

    @patch("ap_common.calibration.get_metadata")
    def test_shorter_exposure_not_allowed(self, mock_get_metadata):
        """Test rejecting shorter exposure darks when not allowed."""
        # Setup mock
        mock_get_metadata.return_value = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_EXPOSURESECONDS: "30.0",
                NORMALIZED_HEADER_GAIN: "100",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "120.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            allow_shorter_exposure=False,
            printStatus=False,
        )

        # Should reject shorter dark when not allowed
        assert len(result) == 0

    @patch("ap_common.calibration.get_metadata")
    def test_no_matches(self, mock_get_metadata):
        """Test when no darks match."""
        mock_get_metadata.return_value = {}

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            printStatus=False,
        )

        assert len(result) == 0

    @patch("ap_common.calibration.get_metadata")
    def test_longer_exposure_rejected(self, mock_get_metadata):
        """Test that longer exposure darks are rejected."""
        # Setup mock
        mock_get_metadata.return_value = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_EXPOSURESECONDS: "180.0",
                NORMALIZED_HEADER_GAIN: "100",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            allow_shorter_exposure=True,  # Even with this, longer should be rejected
            printStatus=False,
        )

        # Longer exposure dark should always be rejected
        assert len(result) == 0

    @patch("ap_common.calibration.get_metadata")
    def test_recursive_vs_nonrecursive(self, mock_get_metadata):
        """Test that recursive parameter is passed correctly."""
        mock_get_metadata.return_value = {}

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
        }

        # Test recursive=True
        find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
            recursive=True,
            printStatus=False,
        )

        # Check that get_filtered_metadata was called with recursive=True
        call_args = mock_get_metadata.call_args
        assert call_args[1]["recursive"] is True

        # Test recursive=False
        find_matching_darks(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
            recursive=False,
            printStatus=False,
        )

        # Check that get_filtered_metadata was called with recursive=False
        call_args = mock_get_metadata.call_args
        assert call_args[1]["recursive"] is False


class TestFindMatchingFlats:
    """Tests for find_matching_flats function."""

    @patch("ap_common.calibration.get_metadata")
    def test_basic_flat_matching(self, mock_get_metadata):
        """Test basic flat matching."""
        mock_get_metadata.return_value = {
            "/path/flat1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/flat1.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_FLAT,
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_FILTER: "Ha",
                NORMALIZED_HEADER_GAIN: "100",
            },
        }

        reference = {
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_FILTER: "Ha",
            NORMALIZED_HEADER_GAIN: "100",
        }

        result = find_matching_flats(
            "/library",
            reference,
            match_fields=[
                NORMALIZED_HEADER_CAMERA,
                NORMALIZED_HEADER_FILTER,
                NORMALIZED_HEADER_GAIN,
            ],
            printStatus=False,
        )

        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_FILTER] == "Ha"

    @patch("ap_common.calibration.get_metadata")
    def test_multiple_flat_matches(self, mock_get_metadata):
        """Test finding multiple matching flats."""
        mock_get_metadata.return_value = {
            "/path/flat1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/flat1.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_FLAT,
                NORMALIZED_HEADER_FILTER: "Ha",
            },
            "/path/flat2.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/flat2.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_FLAT,
                NORMALIZED_HEADER_FILTER: "Ha",
            },
        }

        reference = {NORMALIZED_HEADER_FILTER: "Ha"}

        result = find_matching_flats(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_FILTER],
            printStatus=False,
        )

        assert len(result) == 2

    @patch("ap_common.calibration.get_metadata")
    def test_no_flat_matches(self, mock_get_metadata):
        """Test when no flats match."""
        mock_get_metadata.return_value = {}

        reference = {NORMALIZED_HEADER_FILTER: "Ha"}

        result = find_matching_flats(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_FILTER],
            printStatus=False,
        )

        assert len(result) == 0

    @patch("ap_common.calibration.get_metadata")
    def test_flat_with_date_matching(self, mock_get_metadata):
        """Test flat matching including date field."""
        from ap_common.constants import NORMALIZED_HEADER_DATE

        mock_get_metadata.return_value = {
            "/path/flat1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/flat1.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_FLAT,
                NORMALIZED_HEADER_FILTER: "Ha",
                NORMALIZED_HEADER_DATE: "2024-01-15",
            },
        }

        reference = {
            NORMALIZED_HEADER_FILTER: "Ha",
            NORMALIZED_HEADER_DATE: "2024-01-15",
        }

        result = find_matching_flats(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_FILTER, NORMALIZED_HEADER_DATE],
            printStatus=False,
        )

        assert len(result) == 1


class TestFindMatchingBias:
    """Tests for find_matching_bias function."""

    @patch("ap_common.calibration.get_metadata")
    def test_basic_bias_matching(self, mock_get_metadata):
        """Test basic bias matching."""
        mock_get_metadata.return_value = {
            "/path/bias1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/bias1.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_BIAS,
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "100",
                NORMALIZED_HEADER_OFFSET: "10",
            },
        }

        reference = {
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
            NORMALIZED_HEADER_OFFSET: "10",
        }

        result = find_matching_bias(
            "/library",
            reference,
            match_fields=[
                NORMALIZED_HEADER_CAMERA,
                NORMALIZED_HEADER_GAIN,
                NORMALIZED_HEADER_OFFSET,
            ],
            printStatus=False,
        )

        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_GAIN] == "100"

    @patch("ap_common.calibration.get_metadata")
    def test_multiple_bias_matches(self, mock_get_metadata):
        """Test finding multiple matching bias frames."""
        mock_get_metadata.return_value = {
            "/path/bias1.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/bias1.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_BIAS,
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "100",
            },
            "/path/bias2.fits": {
                NORMALIZED_HEADER_FILENAME: "/path/bias2.fits",
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_BIAS,
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "100",
            },
        }

        reference = {NORMALIZED_HEADER_CAMERA: "ASI2600MM"}

        result = find_matching_bias(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
            printStatus=False,
        )

        assert len(result) == 2

    @patch("ap_common.calibration.get_metadata")
    def test_no_bias_matches(self, mock_get_metadata):
        """Test when no bias frames match."""
        mock_get_metadata.return_value = {}

        reference = {NORMALIZED_HEADER_CAMERA: "ASI2600MM"}

        result = find_matching_bias(
            "/library",
            reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
            printStatus=False,
        )

        assert len(result) == 0


class TestCacheBasedCalibrationFunctions:
    """Tests for *_from_cache calibration functions."""

    def test_find_matching_darks_from_cache(self):
        """Test find_matching_darks_from_cache filters darks from cache."""
        # Create metadata dict
        metadata_dict = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "100",
            },
            "/path/dark2.fits": {
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_FILENAME: "/path/dark2.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "120.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "100",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        # Call with cache
        result = find_matching_darks_from_cache(
            metadata_dict=metadata_dict,
            reference=reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
            allow_shorter_exposure=False,
        )

        # Should find exact exposure match
        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_FILENAME] == "/path/dark1.fits"

    def test_find_matching_flats_from_cache(self):
        """Test find_matching_flats_from_cache filters flats from cache."""
        # Create metadata dict
        metadata_dict = {
            "/path/flat1.fits": {
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_FLAT,
                NORMALIZED_HEADER_FILENAME: "/path/flat1.fits",
                NORMALIZED_HEADER_FILTER: "Ha",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
            "/path/flat2.fits": {
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_FLAT,
                NORMALIZED_HEADER_FILENAME: "/path/flat2.fits",
                NORMALIZED_HEADER_FILTER: "OIII",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {
            NORMALIZED_HEADER_FILTER: "Ha",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
        }

        # Call with cache
        result = find_matching_flats_from_cache(
            metadata_dict=metadata_dict,
            reference=reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_FILTER],
        )

        # Should find Ha flat
        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_FILENAME] == "/path/flat1.fits"

    def test_find_matching_bias_from_cache(self):
        """Test find_matching_bias_from_cache filters bias from cache."""
        # Create metadata dict
        metadata_dict = {
            "/path/bias1.fits": {
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_BIAS,
                NORMALIZED_HEADER_FILENAME: "/path/bias1.fits",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "100",
            },
            "/path/bias2.fits": {
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_BIAS,
                NORMALIZED_HEADER_FILENAME: "/path/bias2.fits",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "200",
            },
        }

        reference = {
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        # Call with cache
        result = find_matching_bias_from_cache(
            metadata_dict=metadata_dict,
            reference=reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
        )

        # Should find gain 100 bias
        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_FILENAME] == "/path/bias1.fits"

    def test_cache_functions_dont_do_disk_io(self):
        """Test that *_from_cache functions don't do disk I/O."""
        # Cache functions operate purely in memory
        # They should work without any file system access
        metadata_dict = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
        }

        # Should work without disk access
        result = find_matching_darks_from_cache(
            metadata_dict=metadata_dict,
            reference=reference,
            match_fields=[NORMALIZED_HEADER_CAMERA],
        )

        # Should return results from cache
        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_FILENAME] == "/path/dark1.fits"

    def test_cache_functions_filter_by_criteria(self):
        """Test *_from_cache functions filter by match criteria correctly."""
        # Create metadata dict with multiple darks
        metadata_dict = {
            "/path/dark1.fits": {
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_FILENAME: "/path/dark1.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "100",
            },
            "/path/dark2.fits": {
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_DARK,
                NORMALIZED_HEADER_FILENAME: "/path/dark2.fits",
                NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "200",  # Different gain
            },
            "/path/flat1.fits": {
                NORMALIZED_HEADER_TYPE: TYPE_MASTER_FLAT,  # Wrong type
                NORMALIZED_HEADER_FILENAME: "/path/flat1.fits",
                NORMALIZED_HEADER_CAMERA: "ASI2600MM",
                NORMALIZED_HEADER_GAIN: "100",
            },
        }

        reference = {
            NORMALIZED_HEADER_EXPOSURESECONDS: "60.0",
            NORMALIZED_HEADER_CAMERA: "ASI2600MM",
            NORMALIZED_HEADER_GAIN: "100",
        }

        # Call with cache
        result = find_matching_darks_from_cache(
            metadata_dict=metadata_dict,
            reference=reference,
            match_fields=[NORMALIZED_HEADER_CAMERA, NORMALIZED_HEADER_GAIN],
        )

        # Should find only dark1 (matches camera+gain, not dark2 or flat1)
        assert len(result) == 1
        assert result[0][NORMALIZED_HEADER_FILENAME] == "/path/dark1.fits"
